teams:
  - name: lf-staff
    maintainers:
      - ryjones
      - jwagantall
    members:
      - christinaharter
      - thelinuxfoundation
  - name: paladin-admins
    maintainers:
      - jimthematrix
    members:
      - matthew1001
  - name: paladin-committers
    maintainers:
      - matthew1001
    members:
      - jimthematrix
      - EnriqueL8
      - awrichar
      - peterbroadhurst
      - Chengxuan
      - dwertent
      - hosie
      - gabriel-indik
      - SamMayWork
      - annamcallister
      - mjc-dev
  - name: zeto-admins
    maintainers:
      - jimthematrix
    members:
      - matthew1001
  - name: zeto-committers
    maintainers:
      - jimthematrix
    members:
      - EnriqueL8
      - awrichar
      - peterbroadhurst
      - Chengxuan
  - name: smt-admins
    maintainers:
      - jimthematrix
    members:
      - matthew1001
  - name: smt-committers
    maintainers:
      - jimthematrix
    members:
      - EnriqueL8
      - awrichar
      - peterbroadhurst
      - Chengxuan
  - name: railgun-admins
    maintainers:
      - jimthematrix
    members:
      - matthew1001
  - name: railgun-committers
    maintainers:
      - jimthematrix
    members:
      - awrichar
      - peterbroadhurst
      - Chengxuan

repositories:
  - name: .github
    teams:
      lf-staff: maintain
      paladin-admins: admin
      paladin-committers: write
    visibility: public
  - name: governance
    teams:
      lf-staff: admin
      paladin-admins: maintain
    visibility: public
  - name: paladin
    teams:
      paladin-admins: admin
      paladin-committers: write
    visibility: public
  - name: zeto
    teams:
      zeto-admins: admin
      zeto-committers: write
    visibility: public
  - name: smt
    teams:
      smt-admins: admin
      smt-committers: write
    visibility: public
  - name: railgun
    teams:
      railgun-admins: admin
      railgun-committers: write
    visibility: public
